### ISSUE TITLE
some improvements?

### ISSUE THREAD

**Issue by diomed** [tailwindtoolbox/Ghostwind#9]
hi

I wondered if I could add some improvements that are unrelated with tailwind.

one would be back to top js button

other would be nice scrollbars , like in vue version.

Also, what do you think about having a multimenu version?
I saw that there is tailwind stripe menu  version available, and that's pretty neat, so I'd incorporate that one.

**Comment by tailwindtoolbox** [comment]
Yeah go for it... make the changes and add a PR and i'll merge in :)

**Comment by diomed** [comment]
please merge

i have problems with multimenu

**Comment by tailwindtoolbox** [comment]
merged in!

**Comment by diomed** [comment]
would be good to add screenshot if possible

**Comment by diomed** [comment]
please merge last commits
